### ISSUE TITLE
TypeError: an integer is required (got type NoneType)

### ISSUE THREAD

**Issue by ykqmain** [SublimeText/StatusBarFileSize#12]
```
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 964, in on_activated_async
    run_view_callbacks('on_activated_async', view_id)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 728, in run_view_callbacks
    callback(v, *args)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime_plugin.py", line 190, in exception_handler
    return event_handler(*args)
  File "/Users/yang/Library/Application Support/Sublime Text/Installed Packages/Status Bar File Size.sublime-package/StatusBarFileSize.py", line 203, in update_file_size_debounced
    sublime.set_timeout_async(partial(self._check_call, view), delay)
  File "/Applications/Sublime Text.app/Contents/MacOS/Lib/python38/sublime.py", line 491, in set_timeout_async
    sublime_api.set_timeout_async(f, timeout_ms)
TypeError: an integer is required (got type NoneType)
```

**Comment by ykqmain** [comment]
macOS 12.3.1 (M1)
Sublime (Build 4126)
Python 3.10.4

**Comment by FichteFoll** [comment]
Well, that's an odd issue. I was sure the bug has been fixed by now, but apparently there are *still* situations where a `Settings.get` call can yield `None` despite having a fallback. Unless you changed your settings to actually read `"typing_delay": null`, which I highly doubt.

Upstream issue: https://github.com/sublimehq/sublime_text/issues/3090
